# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_author_name', models.CharField(max_length=100)),
                ('project_version', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
