# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170131_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
