# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionset_title', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='documents/')),
                ('comment', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionset', to='projects.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='project',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='answer',
            name='check_val',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='questionSet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.QuestionSet'),
            preserve_default=False,
        ),
    ]
